jirou_deep:
  build: .
  container_name: "jirou_deep"
  restart: always
  volumes:
    - "$PWD/model:/app/model:rw"
    - "$PWD/test_images:/app/test_images:rw"
  environment:
    -  CONSUMER_KEY
    -  CONSUMER_SECRET
    -  ACCESS_TOKEN
    -  ACCESS_SECRET
    -  BOT_NAME
    -  MODEL_PREFIX
    -  MODEL_EPOCH
    -  CENTER_CROP
    -  IMAGE_SIZE
    -  RGB_MEAN
    -  LABELS_TXT
